export const ADD_TO_CART = 'ADD_TO_CART'
export const GET_DATA = 'GET_DATA'
export const CHANGE_DATA = 'CHANGE_DATA'
export const CHANGE_NEXT_DATA = 'CHANGE_NEXT_DATA'
export const FORMAT_IMG_URL = 'FORMAT_IMG_URL'
export const FORMAT_SONG_TITLE = 'FORMAT_SONG_TITLE'
